// Generated by scripts/build-apple-weather-scenes.mjs. Do not edit by hand.
import texture_Bolt_Screen_Blind_heic from '../../assets/weather/apple-scene/textures/Bolt-Screen-Blind.webp'
import texture_Bolt_Screen_Flash_heic from '../../assets/weather/apple-scene/textures/Bolt-Screen-Flash.webp'
import texture_Bolt_and_Halo_heic from '../../assets/weather/apple-scene/textures/Bolt-and-Halo.webp'
import texture_Cirrus_One_Overlap_heic from '../../assets/weather/apple-scene/textures/Cirrus-One-Overlap.webp'
import texture_Cirrus_Two_Overlap_heic from '../../assets/weather/apple-scene/textures/Cirrus-Two-Overlap.webp'
import texture_Cloud_Drizzle_heic from '../../assets/weather/apple-scene/textures/Cloud-Drizzle.webp'
import texture_Cloud_Patch_One_heic from '../../assets/weather/apple-scene/textures/Cloud-Patch-One.webp'
import texture_Cloudy_Background_One_heic from '../../assets/weather/apple-scene/textures/Cloudy-Background-One.webp'
import texture_Cumulus_One_Blue_heic from '../../assets/weather/apple-scene/textures/Cumulus-One-Blue.webp'
import texture_Cumulus_One_Neutral_heic from '../../assets/weather/apple-scene/textures/Cumulus-One-Neutral.webp'
import texture_Cumulus_Three_Blue_heic from '../../assets/weather/apple-scene/textures/Cumulus-Three-Blue.webp'
import texture_Cumulus_Three_Neutral_heic from '../../assets/weather/apple-scene/textures/Cumulus-Three-Neutral.webp'
import texture_Cumulus_Two_Blue_heic from '../../assets/weather/apple-scene/textures/Cumulus-Two-Blue.webp'
import texture_Cumulus_Two_Neutral_heic from '../../assets/weather/apple-scene/textures/Cumulus-Two-Neutral.webp'
import texture_Fringe_Large_Blue_heic from '../../assets/weather/apple-scene/textures/Fringe-Large-Blue.webp'
import texture_Fringe_Large_Neutral_heic from '../../assets/weather/apple-scene/textures/Fringe-Large-Neutral.webp'
import texture_Lens_Flare_Medium_heic from '../../assets/weather/apple-scene/textures/Lens-Flare-Medium.webp'
import texture_Meteor_heic from '../../assets/weather/apple-scene/textures/Meteor.webp'
import texture_Raindrop_Cluster_Small_heic from '../../assets/weather/apple-scene/textures/Raindrop-Cluster-Small.webp'
import texture_Raindrop_Tile_Heavy_heic from '../../assets/weather/apple-scene/textures/Raindrop-Tile-Heavy.webp'
import texture_Raindrop_heic from '../../assets/weather/apple-scene/textures/Raindrop.webp'
import texture_Ray_Cyan_heic from '../../assets/weather/apple-scene/textures/Ray-Cyan.webp'
import texture_Snow_Flake_Small_heic from '../../assets/weather/apple-scene/textures/Snow-Flake-Small.webp'
import texture_Star_Frames_heic from '../../assets/weather/apple-scene/textures/Star-Frames.webp'
import texture_Sun_Left_heic from '../../assets/weather/apple-scene/textures/Sun-Left.webp'
import texture_Thunderstorm_Day_Flicker_01_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-01.webp'
import texture_Thunderstorm_Day_Flicker_02_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-02.webp'
import texture_Thunderstorm_Day_Flicker_03_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-03.webp'
import texture_Thunderstorm_Day_Flicker_04_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-04.webp'
import texture_Thunderstorm_Day_Flicker_05_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-05.webp'
import texture_Thunderstorm_Day_Flicker_06_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Flicker-06.webp'
import texture_Thunderstorm_Day_Main_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Day-Main.webp'
import texture_Thunderstorm_Gradient_Bottom_Day_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Gradient-Bottom-Day.webp'
import texture_Thunderstorm_Gradient_Bottom_Night_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Gradient-Bottom-Night.webp'
import texture_Thunderstorm_Night_Flicker_01_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-01.webp'
import texture_Thunderstorm_Night_Flicker_02_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-02.webp'
import texture_Thunderstorm_Night_Flicker_03_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-03.webp'
import texture_Thunderstorm_Night_Flicker_04_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-04.webp'
import texture_Thunderstorm_Night_Flicker_05_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-05.webp'
import texture_Thunderstorm_Night_Flicker_06_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Flicker-06.webp'
import texture_Thunderstorm_Night_Main_heic from '../../assets/weather/apple-scene/textures/Thunderstorm-Night-Main.webp'

export interface AppleWeatherTextureAsset {
  url: string
  width: number
  height: number
  frames: number
}

export const APPLE_WEATHER_TEXTURES: Record<string, AppleWeatherTextureAsset> = {
  "Bolt-Screen-Blind.heic": { url: texture_Bolt_Screen_Blind_heic, width: 1, height: 1136, frames: 1 },
  "Bolt-Screen-Flash.heic": { url: texture_Bolt_Screen_Flash_heic, width: 1, height: 512, frames: 1 },
  "Bolt-and-Halo.heic": { url: texture_Bolt_and_Halo_heic, width: 27, height: 27, frames: 1 },
  "Cirrus-One-Overlap.heic": { url: texture_Cirrus_One_Overlap_heic, width: 1440, height: 360, frames: 1 },
  "Cirrus-Two-Overlap.heic": { url: texture_Cirrus_Two_Overlap_heic, width: 1440, height: 360, frames: 1 },
  "Cloud-Drizzle.heic": { url: texture_Cloud_Drizzle_heic, width: 768, height: 480, frames: 1 },
  "Cloud-Patch-One.heic": { url: texture_Cloud_Patch_One_heic, width: 1024, height: 1024, frames: 1 },
  "Cloudy-Background-One.heic": { url: texture_Cloudy_Background_One_heic, width: 1152, height: 384, frames: 1 },
  "Cumulus-One-Blue.heic": { url: texture_Cumulus_One_Blue_heic, width: 1536, height: 768, frames: 1 },
  "Cumulus-One-Neutral.heic": { url: texture_Cumulus_One_Neutral_heic, width: 1536, height: 768, frames: 1 },
  "Cumulus-Three-Blue.heic": { url: texture_Cumulus_Three_Blue_heic, width: 2048, height: 1024, frames: 1 },
  "Cumulus-Three-Neutral.heic": { url: texture_Cumulus_Three_Neutral_heic, width: 2048, height: 1024, frames: 1 },
  "Cumulus-Two-Blue.heic": { url: texture_Cumulus_Two_Blue_heic, width: 1536, height: 768, frames: 1 },
  "Cumulus-Two-Neutral.heic": { url: texture_Cumulus_Two_Neutral_heic, width: 1536, height: 768, frames: 1 },
  "Fringe-Large-Blue.heic": { url: texture_Fringe_Large_Blue_heic, width: 1024, height: 512, frames: 1 },
  "Fringe-Large-Neutral.heic": { url: texture_Fringe_Large_Neutral_heic, width: 1024, height: 512, frames: 1 },
  "Lens-Flare-Medium.heic": { url: texture_Lens_Flare_Medium_heic, width: 768, height: 192, frames: 1 },
  "Meteor.heic": { url: texture_Meteor_heic, width: 56, height: 128, frames: 1 },
  "Raindrop-Cluster-Small.heic": { url: texture_Raindrop_Cluster_Small_heic, width: 300, height: 100, frames: 1 },
  "Raindrop-Tile-Heavy.heic": { url: texture_Raindrop_Tile_Heavy_heic, width: 500, height: 500, frames: 1 },
  "Raindrop.heic": { url: texture_Raindrop_heic, width: 5, height: 50, frames: 1 },
  "Ray-Cyan.heic": { url: texture_Ray_Cyan_heic, width: 64, height: 512, frames: 1 },
  "Snow-Flake-Small.heic": { url: texture_Snow_Flake_Small_heic, width: 5, height: 5, frames: 1 },
  "Star-Frames.heic": { url: texture_Star_Frames_heic, width: 16, height: 32, frames: 1 },
  "Sun-Left.heic": { url: texture_Sun_Left_heic, width: 240, height: 240, frames: 1 },
  "Thunderstorm-Day-Flicker-01.heic": { url: texture_Thunderstorm_Day_Flicker_01_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Day-Flicker-02.heic": { url: texture_Thunderstorm_Day_Flicker_02_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Day-Flicker-03.heic": { url: texture_Thunderstorm_Day_Flicker_03_heic, width: 300, height: 480, frames: 1 },
  "Thunderstorm-Day-Flicker-04.heic": { url: texture_Thunderstorm_Day_Flicker_04_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Day-Flicker-05.heic": { url: texture_Thunderstorm_Day_Flicker_05_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Day-Flicker-06.heic": { url: texture_Thunderstorm_Day_Flicker_06_heic, width: 440, height: 480, frames: 1 },
  "Thunderstorm-Day-Main.heic": { url: texture_Thunderstorm_Day_Main_heic, width: 1840, height: 480, frames: 1 },
  "Thunderstorm-Gradient-Bottom-Day.heic": { url: texture_Thunderstorm_Gradient_Bottom_Day_heic, width: 16, height: 664, frames: 1 },
  "Thunderstorm-Gradient-Bottom-Night.heic": { url: texture_Thunderstorm_Gradient_Bottom_Night_heic, width: 16, height: 664, frames: 1 },
  "Thunderstorm-Night-Flicker-01.heic": { url: texture_Thunderstorm_Night_Flicker_01_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Night-Flicker-02.heic": { url: texture_Thunderstorm_Night_Flicker_02_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Night-Flicker-03.heic": { url: texture_Thunderstorm_Night_Flicker_03_heic, width: 300, height: 480, frames: 1 },
  "Thunderstorm-Night-Flicker-04.heic": { url: texture_Thunderstorm_Night_Flicker_04_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Night-Flicker-05.heic": { url: texture_Thunderstorm_Night_Flicker_05_heic, width: 480, height: 480, frames: 1 },
  "Thunderstorm-Night-Flicker-06.heic": { url: texture_Thunderstorm_Night_Flicker_06_heic, width: 440, height: 480, frames: 1 },
  "Thunderstorm-Night-Main.heic": { url: texture_Thunderstorm_Night_Main_heic, width: 1840, height: 480, frames: 1 },
}

export const APPLE_WEATHER_SCENES = {
  "clear-day": {
    "id": "clear-day",
    "caml": "sunny@3x-812h.caml",
    "hash": "96d82d612b546bc42d7bba5993dfbc3becaa31e7bfba468e98c0f5e634a6a1af",
    "assets": [
      "Lens-Flare-Medium.heic",
      "Sun-Left.heic",
      "Ray-Cyan.heic"
    ]
  },
  "clear-night": {
    "id": "clear-night",
    "caml": "clear@3x-812h.caml",
    "hash": "50fb481f7a129759023edb84c5736874e792d420413e98c29bec35017a7d2378",
    "assets": [
      "Star-Frames.heic",
      "Meteor.heic"
    ]
  },
  "partly-cloudy-day": {
    "id": "partly-cloudy-day",
    "caml": "partlyCloudy_day@3x-812h.caml",
    "hash": "763e97b32497c09286cc303652506fe844dc76e685df3589a9db52cb35aae2eb",
    "assets": [
      "Sun-Left.heic",
      "Cirrus-One-Overlap.heic",
      "Cirrus-Two-Overlap.heic",
      "Cumulus-One-Blue.heic",
      "Fringe-Large-Blue.heic",
      "Cumulus-Two-Blue.heic",
      "Ray-Cyan.heic",
      "Cumulus-Three-Blue.heic"
    ]
  },
  "partly-cloudy-night": {
    "id": "partly-cloudy-night",
    "caml": "partlyCloudy_night@3x-812h.caml",
    "hash": "809b5cd3628b13da93930ad7efa47980794d690d65e6841b207402954699166a",
    "assets": [
      "Star-Frames.heic",
      "Cirrus-One-Overlap.heic",
      "Cirrus-Two-Overlap.heic",
      "Cumulus-One-Neutral.heic",
      "Fringe-Large-Neutral.heic",
      "Cumulus-Two-Neutral.heic",
      "Cumulus-Three-Neutral.heic"
    ]
  },
  "cloudy-day": {
    "id": "cloudy-day",
    "caml": "cloudy_day@3x-812h.caml",
    "hash": "44a5e7548a67996777e21f5c73a5471fb433d549c75c72eaa2fe935c07169549",
    "assets": [
      "Cloudy-Background-One.heic",
      "Cumulus-One-Neutral.heic",
      "Fringe-Large-Neutral.heic",
      "Cumulus-Two-Neutral.heic",
      "Cumulus-Three-Neutral.heic"
    ]
  },
  "cloudy-night": {
    "id": "cloudy-night",
    "caml": "cloudy_night@3x-812h.caml",
    "hash": "713580dae612bd5a8cca00e674020ac148315f6ee89d1eee68de9d5e733f882e",
    "assets": [
      "Cloudy-Background-One.heic",
      "Cumulus-One-Neutral.heic",
      "Fringe-Large-Neutral.heic",
      "Cumulus-Two-Neutral.heic",
      "Cumulus-Three-Neutral.heic"
    ]
  },
  "fog-day": {
    "id": "fog-day",
    "caml": "fog_day@3x-812h.caml",
    "hash": "d78dbdd1f7b6ed31c6ae90e513a03beaa7e69f4caf6489464296e171078f7999",
    "assets": [
      "Cloud-Patch-One.heic"
    ]
  },
  "fog-night": {
    "id": "fog-night",
    "caml": "fog_night@3x-812h.caml",
    "hash": "72a4a083088f6c6a770add875c75e48479f509e77e33ef770453153041c8e9de",
    "assets": [
      "Cloud-Patch-One.heic"
    ]
  },
  "drizzle-day": {
    "id": "drizzle-day",
    "caml": "drizzle_day@3x-812h.caml",
    "hash": "07e8c7d5b57979b518f86f72fe87223b5a01dc2e9d28414ed65bb9683cf2485e",
    "assets": [
      "Cloud-Drizzle.heic",
      "Raindrop.heic"
    ]
  },
  "drizzle-night": {
    "id": "drizzle-night",
    "caml": "drizzle_night@3x-812h.caml",
    "hash": "3ec7384360e5d6fec556aed8a38485448afb30c90bb02d27a794da69bc45a303",
    "assets": [
      "Cloud-Drizzle.heic",
      "Raindrop.heic"
    ]
  },
  "rain-day": {
    "id": "rain-day",
    "caml": "rain_day@3x-812h.caml",
    "hash": "f2e783a69cb9ce2d173546ed5357b77dc5f29d0e78d786c8ed039aa7cb6e8a69",
    "assets": [
      "Raindrop-Tile-Heavy.heic",
      "Raindrop.heic"
    ]
  },
  "rain-night": {
    "id": "rain-night",
    "caml": "rain_night@3x-812h.caml",
    "hash": "cda9b15297afd1604803f6b6007db1947f0c8be9792561f26b6b4efaabc66395",
    "assets": [
      "Raindrop-Tile-Heavy.heic",
      "Raindrop.heic"
    ]
  },
  "heavy-rain-day": {
    "id": "heavy-rain-day",
    "caml": "heavyRain_day@3x-812h.caml",
    "hash": "17a0aa89f632fa1ecc549a5310119f0098b074f0e3a6a9ea451788c05493ba4c",
    "assets": [
      "Raindrop-Tile-Heavy.heic",
      "Raindrop.heic"
    ]
  },
  "heavy-rain-night": {
    "id": "heavy-rain-night",
    "caml": "heavyRain_night@3x-812h.caml",
    "hash": "55279ecab2cb7d531c56c4b4deac614b1132ed6887ef8fe9410798b37b94e919",
    "assets": [
      "Raindrop-Tile-Heavy.heic",
      "Raindrop.heic"
    ]
  },
  "thunder-day": {
    "id": "thunder-day",
    "caml": "thunderstorm_day@3x-812h.caml",
    "hash": "9b02ce67b39435e0d6531d41713821ce101faf5fee06ef8a22d31cb45c465aac",
    "assets": [
      "Thunderstorm-Gradient-Bottom-Day.heic",
      "Thunderstorm-Day-Main.heic",
      "Thunderstorm-Day-Flicker-01.heic",
      "Thunderstorm-Day-Flicker-02.heic",
      "Thunderstorm-Day-Flicker-03.heic",
      "Thunderstorm-Day-Flicker-04.heic",
      "Thunderstorm-Day-Flicker-05.heic",
      "Thunderstorm-Day-Flicker-06.heic",
      "Bolt-and-Halo.heic",
      "Bolt-Screen-Flash.heic",
      "Bolt-Screen-Blind.heic",
      "Raindrop-Tile-Heavy.heic",
      "Raindrop-Cluster-Small.heic",
      "Raindrop.heic"
    ]
  },
  "thunder-night": {
    "id": "thunder-night",
    "caml": "thunderstorm_night@3x-812h.caml",
    "hash": "9bd1076701e2cb8290b67b9244ba396d635c3ec806048a5e55cf18b8e2273d65",
    "assets": [
      "Thunderstorm-Gradient-Bottom-Night.heic",
      "Thunderstorm-Night-Main.heic",
      "Thunderstorm-Night-Flicker-01.heic",
      "Thunderstorm-Night-Flicker-02.heic",
      "Thunderstorm-Night-Flicker-03.heic",
      "Thunderstorm-Night-Flicker-04.heic",
      "Thunderstorm-Night-Flicker-05.heic",
      "Thunderstorm-Night-Flicker-06.heic",
      "Bolt-and-Halo.heic",
      "Bolt-Screen-Flash.heic",
      "Bolt-Screen-Blind.heic",
      "Raindrop-Tile-Heavy.heic",
      "Raindrop-Cluster-Small.heic",
      "Raindrop.heic"
    ]
  },
  "snow-day": {
    "id": "snow-day",
    "caml": "snow_day@3x-812h.caml",
    "hash": "3b439c259909908208ee7bc6c810379851dc25bb6429103ad4fbe34505774d5e",
    "assets": [
      "Snow-Flake-Small.heic"
    ]
  },
  "snow-night": {
    "id": "snow-night",
    "caml": "snow_night@3x-812h.caml",
    "hash": "4e9f807134b6b61e78d1ce6214db6dbdd71be2f2481f68faf0253d528ef95d57",
    "assets": [
      "Snow-Flake-Small.heic"
    ]
  }
} as const
