// HyperPlayer adaptations: HSE v1.5.1 快照缺少 dist/ 与 scripts/（vendored 时未携带），
// 此脚本按 HSE 文档产物规格重建：
//   dist/index.js          —— 核心内核（Node + 浏览器通用）
//   dist/browser.js        —— 浏览器宿主（HyperSoundEngineHost）
//   dist/worklet.js        —— AudioWorklet 打包入口（声明面）
//   dist/worklet-bundle.js —— AudioWorklet 单文件 IIFE（audioWorklet.addModule）
//   dist/*.d.ts            —— 类型声明（tsc 从 src 生成）
// 构建产物不提交；每次 install 后由 pnpm 脚本触发（见根 package.json build:hse）。
// 依赖：esbuild + typescript（HSE devDependencies，本地安装）。

import { build } from 'esbuild'
import { execFileSync } from 'node:child_process'
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const hseRoot = resolve(here, '../shared/hypersoundengine')
const src = resolve(hseRoot, 'src')
const dist = resolve(hseRoot, 'dist')
const publicDir = resolve(here, '../public')

mkdirSync(dist, { recursive: true })

const common = {
  bundle: true,
  platform: 'browser',
  format: 'esm',
  target: 'es2022',
  logLevel: 'warning',
  // worklet 依赖 node-forge？否。HSE 纯 TS，无外部运行时依赖。
  absWorkingDir: hseRoot,
}

// 1) 核心内核
await build({ ...common, entryPoints: [resolve(src, 'index.ts')], outfile: resolve(dist, 'index.js') })
// 2) 浏览器宿主
await build({ ...common, entryPoints: [resolve(src, 'browser.ts')], outfile: resolve(dist, 'browser.js') })
// 3) AudioWorklet 单文件 IIFE（渲染线程，无 ESM import/export）
await build({
  ...common,
  entryPoints: [resolve(src, 'worklet.ts')],
  outfile: resolve(dist, 'worklet-bundle.js'),
  format: 'iife',
})

// 4) 类型声明：tsc 从 src 生成（HSE 文档 build:types 步骤）
const tsconfig = resolve(hseRoot, 'tsconfig.build.json')
if (!exists(tsconfig)) {
  // 快照未携带 tsconfig.build.json：按 HSE 文档的声明面直接复制 src 类型入口
  console.log('[build-hse] tsconfig.build.json 缺失，跳过 tsc 类型构建（Vite 运行时不受影响）')
} else {
  execFileSync(resolve(hseRoot, 'node_modules/.bin/tsc'), ['-p', tsconfig], { stdio: 'inherit', cwd: hseRoot })
}

// 5) 类型声明：dist/*.d.ts 以 re-export 指向 src（tsc bundler 解析；
//    快照未携带 tsconfig.build.json，不生成完整声明产物）
const dtsShims = {
  'index.d.ts': "export * from '../src/index'\n",
  'browser.d.ts': "export * from '../src/browser'\n",
  'worklet.d.ts': "export * from '../src/worklet'\n",
}
for (const [name, content] of Object.entries(dtsShims)) {
  writeFileSync(resolve(dist, name), `// GENERATED by scripts/build-hse.mjs — do not edit\n${content}`, 'utf-8')
}

console.log('[build-hse] dist 产物已生成：', readFileSync(resolve(dist, 'index.js'), 'utf-8').length, 'bytes (index)')

// 6) worklet bundle 复制到 Vite public 目录（audioWorklet.addModule 需可经 URL 加载；
//    public/ 会原样复制到构建产物根，dev 下经 /hse-worklet-bundle.js 访问）
mkdirSync(publicDir, { recursive: true })
cpSync(resolve(dist, 'worklet-bundle.js'), resolve(publicDir, 'hse-worklet-bundle.js'))
console.log('[build-hse] worklet bundle → public/hse-worklet-bundle.js')

function exists(p) {
  try {
    readFileSync(p)
    return true
  } catch {
    return false
  }
}
