/**
 * 网易云音源模块出口（全量端点）。
 * 依据：docs/音源-网易云-行为规范.md（Cleanroom，D15）。
 * 落位：src/audio-source/netease/（主进程侧，架构定稿后整体迁移）。
 */
export * from './types'
export { NeteaseApiError, ensureNetworkReady, registerAnonymous, type CallOptions } from './request'

/** 核心：搜索/歌曲/播放地址/歌词/歌单读取/推荐/FM */
export {
  getAlbumDetail,
  getLyric,
  getNewSongs,
  getPersonalFm,
  getPersonalFmBatched,
  getPersonalizedNewSongs,
  getPersonalizedPlaylists,
  getPlaymodeIntelligenceList,
  getPlaylistDetail,
  getPlaylistTracks,
  getQualityCandidates,
  getRankSongs,
  getRecommendPlaylists,
  getRecommendSongs,
  getSimilarSongs,
  getSongDetail,
  getSongDetailEnriched,
  getSongQualityLevels,
  getSongRelatedBlogs,
  getSongUrl,
  getSongWiki,
  getSongPlayInfo,
  searchHot,
  searchSongs,
  searchSuggest,
  trashFmSong,
  dislikeRecommendSong,
  mapAlbum,
  mapArtist,
  mapPlaylistSummary,
  mapTrack,
} from './client-core'

/** 目录：专辑/歌手/MV/电台/歌单浏览与管理 */
export {
  createPlaylist,
  deletePlaylist,
  getAlbumCoversBatch,
  getAlbumSublist,
  getArtistAlbums,
  getArtistList,
  getArtistMvs,
  getArtistOverview,
  getArtistSongs,
  getArtistSublist,
  getBanner,
  getDjCategories,
  getDjProgramToplist,
  getDjPrograms,
  getDjRecommend,
  getDjSublist,
  getHighQualityPlaylists,
  getHotDjRadios,
  getMvAll,
  getMvDetail,
  getMvPlayInfo,
  getMvSublist,
  getPersonalizedDjRadios,
  getPlaylistCategories,
  getRelatedPlaylists,
  getSimilarArtists,
  getSimilarMvs,
  getSimilarPlaylists,
  getSimilarPlaylistsBySong,
  getTopAlbums,
  getTopArtists,
  getTopMvs,
  getTopPlaylists,
  getToplistDetail,
  getToplistSongs,
  manipulatePlaylistTracks,
  subscribeAlbum,
  subscribeArtist,
  subscribeDjRadio,
  subscribeMv,
  subscribePlaylist,
  updatePlaylist,
  updatePlaylistCover,
} from './client-catalog'

/** 社交：喜欢/评论/动态/消息/关注 */
export {
  addComment,
  checkSongsLiked,
  deleteComment,
  followUser,
  getCommentFloor,
  getComments,
  getFollowedEvents,
  getHotComments,
  getLikeList,
  getMsgComments,
  getMsgNotices,
  getUserEvents,
  getUserFolloweds,
  getUserFollows,
  likeComment,
  likeSong,
  replyComment,
} from './client-social'

/** 用户：账号/记录/云盘/VIP/足迹/journey */
export {
  checkLoginQrState,
  createLoginQrKey,
  deleteCloudSong,
  getCloudDiskSongs,
  getCloudSongUrl,
  getJourneyOverview,
  getListenDataReport,
  getListenDataSongRank,
  getListenDataToday,
  getListenDataTotal,
  getLoginQrImageUrl,
  getLoginStatus,
  getRecentPlays,
  getStylePreference,
  getUserAccount,
  getUserDetail,
  getUserLevel,
  getUserPlayRecord,
  getUserPlaylists,
  getUserSubcount,
  getVipInfo,
  scrobble,
} from './client-user'

/** 探索聚合 */
export {
  getExploreNetease,
  getExploreNext,
  type ExploreChart,
  type ExploreChannel,
  type ExploreNextResult,
  type ExploreResult,
} from './client-explore'
